### ISSUE TITLE
Summer/Fall 2024 release

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#105]
### Summer/early fall
REVIEW state by October 5

**NEW**

- version date 2024-10-31
- version n 6.0.0

- [ ] OCR'd material in GitDox (requires sentence splitting, auto-NLP); see [OCR google doc from June](https://docs.google.com/document/d/123PQhSnMucomyiMhZpzHOLJjWBtXdRijNRNcWR_JTOM/edit?usp=sharing) for details
   - **Do not check off until checked off in the [OCR checklist issue](https://github.com/CopticScriptorium/OCR/issues/1)**
   - [ ] apocalypse.paul (2)
   - [x] mercurius (3)
   - [ ]  Ps Cyril of Alexandria on Mary
   - [ ] ps Cyril of Jerusalem on the cross (3 docs)
   - [ ]  ps Cyril of Jerusalem on Mary
   - [ ]  ps John Chrysostom on Raphael
   - [ ] psepiphanius
   - [ ] pscelestinus
   - [ ] pstimothy.alex
   - [ ] psote.psoi
   - [ ] timothy.discourse

- [ ] fully automatic tagging of OCR data in https://github.com/CopticScriptorium/OCR/tree/main/Processed%20OCR
   - **Do not check off until checked off in the [OCR checklist issue](https://github.com/CopticScriptorium/OCR/issues/1)**
   - [x] Budge
   - [ ] Giron
   - [x] Lacau-Pilate
   - [x] Lacau-Lament
   - [x] Sobhy

- [x] Habakkuk Bohairic
- [x] Theophilus on Continence (??)
- [x] Life of Isaac (Bohairic)
- [x] AP (with Arabic translations) (do not check off until [this thread](https://github.com/CopticScriptorium/ap-dev/issues/100) is complete)

- [x] A22 (do not check off until [this thread](https://github.com/CopticScriptorium/shenoute-a22-dev/issues/58) is complete)

- [x] Bohairic Bible corpus

### Late Fall/winter
- [ ] Crislip material?
- [ ] New Coptic Sahidic OT edition? (@ctschroeder will contact Frank)
- [ ] So Listen (do not check off until [this thread](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/5) is complete)
- [ ] Nag Hammadi Marcion (do not check off until [this issue](https://github.com/CopticScriptorium/nag-hammadi-dev/issues/1) is complete)
   - [ ] G Thomas 
   - [ ] G Philip 
- [ ] Tito's editions? (need conversion to unicode, versification, metadata)
    - [ ] Encomium on Raphael
    - [ ] Cyril ?
- [ ] Other Marcion? (full NLP, need versification & metadata)
   - [x] Encomium on St John the Baptist (6k words)
   - [ ] Resurrection of Jesus Christ (13 k words)
- [x] Bohairic Isaac (from OCR)

### Fall or Spring 2025
- [ ] Life of Phib (translations added?)
- [ ] Life of Aphou (translations added?)
- [ ] Jonah dialects (@EarlyCodices)
- [ ] Life of Shenoute (Bohairic)
- [ ] RK's Life of Hilaria (Sahidic)??
- [ ] Sahidic Life of Antony (from HT, see June 2024 meeting notes)

**Comment by ctschroeder** [comment]
List has been updated! Also @amir-zeldes there is so much I am putting the version date as 2024-10-31. There is so much material from OCR that i'm listing the version n as 6.0.0. If you want to change ether of those lmk; I know it's possible for you to overwrite.

**Comment by amir-zeldes** [comment]
OK, I think Boh. Hab. is ready except for the Coptic_edition metadatum - @ctschroeder is there something we can reference here or just leave blank? Or not include at all?

**Comment by ctschroeder** [comment]
Mercurius is ready @amir-zeldes 
Re Boh Hab: the edition is wherever you got the text. Is this Marcion?

**Comment by amir-zeldes** [comment]
OK, mercurius imports correctly and you can see it in ANNIS if you're logged in. The first two documents are maybe loadable but slow, but I'd say martyrdom.miracles.mercurius is pretty much out of the question in terms of loading time. Would you like me to divide it into two documents?

Habakkuk is from Marcion, I'm not sure what to write in the metadata

**Comment by ctschroeder** [comment]
> OK, mercurius imports correctly and you can see it in ANNIS if you're logged in. The first two documents are maybe loadable but slow, but I'd say martyrdom.miracles.mercurius is pretty much out of the question in terms of loading time. Would you like me to divide it into two documents?
> 
Sure -- just be sure to adjust all the metadata (pages to/from, cts urn, next, previous)

> Habakkuk is from Marcion, I'm not sure what to write in the metadata
It looks like for Bohairic NT we do not have a Coptic_edition field in the metadata. I'd do the same: source is Hany Takla, Marcion Project in both doc & corpus metadata; no Coptic edition for now

**Comment by amir-zeldes** [comment]
OK, split is done and visible in ANNIS with login. Encomium is still pretty slow to render the document view in ANNIS, but I guess that's not a commonly used function anyway. It doesn't time out though, and miracles is fine too.

**Comment by ctschroeder** [comment]
@amir-zeldes ap is ready to publish and [a22 is ready except for identities for the new doc](https://github.com/CopticScriptorium/shenoute-a22-dev/issues/58#issuecomment-2448387153)

**Comment by ctschroeder** [comment]
@amir-zeldes lacau lament of mary and acts of pilate done with corpus metadata (note corrected corpus meta in acts.pilate)

**Comment by ctschroeder** [comment]
@amir-zeldes Bohairic life of Isaac is assigned to me as to_publish, but it looks like the metadata needs a lot of help so pls don't publish yet

**Comment by ctschroeder** [comment]
@amir-zeldes Bohairic life of isaac is ready; throwing validation errors for Coptic edition and facsimile (which doesn't seem correct since we use that format all the time for edition and facsimile)

**Comment by ctschroeder** [comment]
@amir-zeldes pseudo.theophilus is ready EXCEPT corpus metadata annotation needs to be edited. GitDox would not let me change it. Should be: Caroline T. Schroeder, Alin Suciu, Elizabeth Platte, Lydia Bremer-McCollum, Amir Zeldes

**Comment by amir-zeldes** [comment]
> throwing validation errors for Coptic edition and facsimile

Yeah, you're not allowed to use double quotes in metadata values (or annotation values for that matter) - for hyperlinks you should just use single quotes instead, or if you really want double quotes in a human visible part, you can either use smart quotes (round ones), or if you have to have straight double quotes, then `&quot;`.

Not sure what the issue with theophilus was but I was able to fix its🤷‍♂️

**Comment by ctschroeder** [comment]
@amir-zeldes Helias document breaks and corresponding metadata for document/next/previous urns+idno+pages to/from have been adjusted. Documents break at manuscript page breaks (for diplomatic viz) where there are clean word breaks (not necess sentence or bound group but at least words are not broken).
The exception is the first page of the encomium, which is at the end of the last page of the martyrdom. So I added a note to the note metadatum saying the line numbers in the diplomatic viz may not be correct. Best we can do

**Comment by ctschroeder** [comment]
remaining docs have been rescheduled
