### ISSUE TITLE
Early 2025 Corpora Release

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#128]
### Timeline

- REVIEW state by date TBA
- version date TBA
- version n 6.1.0 (probably)

### OCR @ctschroeder 
- [ ] OCR'd material in GitDox (requires sentence splitting, auto-NLP); see [OCR google doc from June](https://docs.google.com/document/d/123PQhSnMucomyiMhZpzHOLJjWBtXdRijNRNcWR_JTOM/edit?usp=sharing) for details
   - **Do not check off until checked off in the [OCR checklist issue](https://github.com/CopticScriptorium/OCR/issues/3)**
   - [ ] apocalypse.paul (2)
   - [ ]  Ps Cyril of Alexandria on Mary
   - [ ] ps Cyril of Jerusalem on the cross (3 docs)
   - [ ]  ps Cyril of Jerusalem on Mary
   - [ ]  ps John Chrysostom on Raphael
   - [ ] psepiphanius
   - [ ] pscelestinus
   - [ ] pstimothy.alex
   - [ ] psote.psoi
   - [ ] timothy.discourse
   - [ ] should be placed in https://github.com/CopticScriptorium/auto-corpora

- [ ] fully automatic tagging of OCR data in https://github.com/CopticScriptorium/OCR/tree/main/Processed%20OCR
   - **Do not check off until checked off in the [OCR checklist issue](https://github.com/CopticScriptorium/OCR/issues/3)**
   - [ ] Giron
   - [ ] should be placed in https://github.com/CopticScriptorium/auto-corpora

### Other fully automatic corpora @amir-zeldes + ??
- [ ] Sahidic CoptOT corpus
- [ ] Other Marcion? (full NLP, need versification & metadata)
   - [ ] Resurrection of Jesus Christ (13 k words)
   - [ ] should be placed in https://github.com/CopticScriptorium/auto-corpora or GitDox

### Manually annotated corpora
- [ ] AP (new + Arabic translations) (do not check off until [this thread](https://github.com/CopticScriptorium/ap-dev/issues/102) is complete) @cluckmarq 

- [ ] A22 (do not check off until [this thread](https://github.com/CopticScriptorium/shenoute-a22-dev/issues/59) is complete) @bkrawiec 

- [ ] Crislip material @ctschroeder 

- [ ] So Listen (do not check off until [this thread](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/5) is complete) @ctschroeder 

- [ ] Nag Hammadi Marcion (do not check off until [this issue](https://github.com/CopticScriptorium/nag-hammadi-dev/issues/1) is complete)
   - [ ] G Philip 

- [ ] Paul Dilley's G Thomas @PaulCDilley 

- [ ] Tito's editions? (need conversion to unicode, versification, metadata)
    - ** needs annotator assigned **
    - [ ] Encomium on Raphael
    - [ ] Cyril ?

Questionable:
- [ ] Life of Phib (translations added?)
- [ ] Life of Aphou (translations added?)
- [ ] Jonah dialects (@EarlyCodices @stepcla)
- [ ] Life of Shenoute (Bohairic)
- [ ] RK's Life of Hilaria (Sahidic)??
- [ ] Sahidic Life of Antony (from HT, see June 2024 meeting notes)

**Comment by amir-zeldes** [comment]
This is a data issue - I've fixed it in GD and it should resolve once we re-release the AP corpus.

**Comment by ctschroeder** [comment]
@amir-zeldes did we do anything with the "questionable corpora" in this issue, or should I move them all forward?

**Comment by amir-zeldes** [comment]
B Jonah should be easy to do, it's already in GD, though it's missing metadata and I'm not sure which layers have been checked (do you remember @EarlyCodices ?). Not sure what the status is for the rest.

**Comment by EarlyCodices** [comment]
> B Jonah should be easy to do, it's already in GD, though it's missing metadata and I'm not sure which layers have been checked (do you remember [@EarlyCodices](https://github.com/EarlyCodices) ?). Not sure what the status is for the rest.

Bo Jonah should just need entities and metadata, otherwise good to go (I don't remember Amir doing spot check, hence status as "review").

**Comment by amir-zeldes** [comment]
OK, thanks - we're not doing gold entities for Jonah since it's not treebanked yet, but we will need metadata if we want to release it as a corpus with checked annotations. @EarlyCodices it's not urgent but if you can put it on your to-do list for whenever you're done higher priorities and have some capacity that would be good (should be copyable/adaptable from Habakkuk)

**Comment by EarlyCodices** [comment]
@amir-zeldes no problem; I've added metadata for Bo Jonah (adapted from Bo Hab).

**Comment by ctschroeder** [comment]
I am making a [separate issue for Bohairic Jonah](https://github.com/CopticScriptorium/bible-dev/issues/78) so we can close this publication thread.

**Comment by amir-zeldes** [comment]
Thanks!

**Comment by ctschroeder** [comment]
have transferred everything open to new issues, esp https://github.com/CopticScriptorium/corpora/issues/137
