### ISSUE TITLE
Winter/Spring 2022 Publication Thread

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#86]
### Proposed timeline TBD

- Freeze list of corpora and documents
- Documents made available for review on Gitdox March 8
- review and prep for publication
- Data freeze/version date TBD

### Corpora
- [x] Abraham Our Father ([see repo issue for details](https://github.com/CopticScriptorium/shenoute-abraham-dev/issues/23); do not check off until issue is complete)
- [x] AP ([see repo issue for details](https://github.com/CopticScriptorium/ap-dev/issues/92); do not check off until issue is complete)
- [x] Pisenthius (@tsiuda is typing in missing section)
- [x] Eustathius and Theopiste
   - [x] Complete checklist in Budge-dev [#12](https://github.com/CopticScriptorium/budge-dev/issues/12).
- [x] shenoute.prince (corrections from Philippe Zaher)
   - [x] need corpus version and date
   - [x] XH185-194 needs version and date
- [x] Pistis Sophia ([repo issue](https://github.com/CopticScriptorium/pistis-sophia-dev/issues/1)); do not check off until issue is complete

### Moved to Summer 2022
- A22
- G Thomas

**Comment by ctschroeder** [comment]
@amir-zeldes @lancealanmartin can you add your corpora to the list? And make publication threads in the relevant repos? Thanks so much!!!

**Comment by amir-zeldes** [comment]
@lancealanmartin Eustathius and Theophiste should definitely be included, can you start the thread for that in Budge-dev?

**Comment by tsiuda** [comment]
I finished keying in Pisenthius today btw! Let me know what else I need to do besides committing it. Thanks!

**Comment by amir-zeldes** [comment]
Wonderful, thank you! I will take a look at moving Pisentius to the next step. In the meantime if one half of Eustathius & Theopiste still needs translations, that would be a good next thing to concentrate on.

**Comment by ctschroeder** [comment]
I've been trying to go through these. There are a few remaining issues. I know everyone is working so this not a nag, more just a check in. Please see individual publication threads in the corpora for remaining tasks.  Thanks!!

**Comment by amir-zeldes** [comment]
@ctschroeder I see the prince document is assigned to you - is it just missing the date? Let me know and I can add that.

**Comment by ctschroeder** [comment]
@amir-zeldes sorry about that. Yeah, prince just needs the version and date in the doc and the corpus and then it can be published

**Comment by amir-zeldes** [comment]
OK done!

**Comment by ctschroeder** [comment]
@amir-zeldes AP is also ready

**Comment by ctschroeder** [comment]
I do not see a test version of Abraham.  Can you load that for me @amir-zeldes ? Thanks!

AP & Prince are fine.

also: Pisentius and E/Th need to be reloaded due to small metadata updates (commas removed from titles) and then they are fine.

See Pistis Sophia thread on that corpus

**Comment by ctschroeder** [comment]
I think Abraham is fine! The Arabic is the only thing added and it seems fine. Metadata is fine

**Comment by amir-zeldes** [comment]
We're good to go, just need to make that GH release archive before closing this issue!

**Comment by amir-zeldes** [comment]
Done!
