### ISSUE TITLE
Summer 2022 release thread

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#90]
### Timeline
Primary editors work freezes 9/10-9/13.
Publication ~9/20

### Tentative Corpora
Shenoute Abraham (Arabic translations by Philippe Zaher)

Amélineau (@lancealanmartin)
- [x] [shenoute.place.BV277-278](https://github.com/CopticScriptorium/shenoute-canons9-dev/issues/2)
- [x] [shenoute.thundered.GG19-28](https://github.com/CopticScriptorium/shenoute-discourses4-dev/issues/10)
- [x] [shenoute.considering.BV283-284](https://github.com/CopticScriptorium/shenoute-canons9-dev/issues/3)

Shenoute A22 (@bkrawiec)
- [x] do not check off until [repo thread is complete](https://github.com/CopticScriptorium/shenoute-a22-dev/issues/54)

Check on Shenoute Abraham ([Arabic translations](https://github.com/CopticScriptorium/shenoute-abraham-dev/issues/23) )
- [x] whole corpus

AP

- [x] do not check off until [repo thread is complete](https://github.com/CopticScriptorium/ap-dev/issues/93)

Pistis Sophia Book 1 (align translation TS) & Pistis Sophia Book 2

- [x] chapter divisions by @lancealanmartin 
- [x] do not check off until rep thread is complete https://github.com/CopticScriptorium/pistis-sophia-dev/issues/2
- [x] also see [alignment issue](https://github.com/CopticScriptorium/pistis-sophia-dev/issues/2)

### Wait until later release
-  [shenoute.listen.XO35-42](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/1)
-  [shenoute.listen.FL15-28](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/1)
- [shenoute.true.BV119-122](https://github.com/CopticScriptorium/shenoute-canons9-dev/issues/3)

Gospel of Thomas

Other Marcion

-  Encomium on St John the Baptist
-  Theophilus on Repentence & Continence (?)
-  Resurrection of Jesus Christ

**Comment by ctschroeder** [comment]
@bkrawiec @cluckmarq @PhilippeZaher any work you're doing right now can be published in the next round if you get it done around the 10th of September. (Earlier is great.) If the summer server outages mean that you didn't get anything done just let me know.

**Comment by ctschroeder** [comment]
@lancealanmartin can you list the repos the Amélineau material are in and the corresponding works we will be publishing this round?

**Comment by lancealanmartin** [comment]
I created issues with rudimentary checklists in the repos and linked the docs to them.

**Comment by ctschroeder** [comment]
Are we publishing those Marcion docs this go around? @amir-zeldes If so, what repo are they in? should I be researching the metadata? Thanks!

**Comment by amir-zeldes** [comment]
I don't think we'll manage those marcions, they aren't really processed yet and PS is taking insane amounts of time due to checking identities and the absolute flood of names (with mangled tokenization) in this work. 

But I thought we *were* planning to include shenoute.considering, does something speak against it?

**Comment by ctschroeder** [comment]
@amir-zeldes https://github.com/CopticScriptorium/shenoute-discourses5-dev/issues/51#issuecomment-1252810929

**Comment by ctschroeder** [comment]
Adding items here that I notice

shenoute.a22
- [ ] in shenoute.a22 YA 303-304 diplomatic is wonky (legacy we didn't catch?); I fixed the pb_xml_id column in gitdox (it was named wrong and there were spaces between the YA and 303 or 304)
- [ ] I cannot figure out what is going on with the diplomatic viz for YA 309-10 in shenoute.a22.  309 column 2 lines 13-16 the letters are all supposed to be small and there is not supposed to be a blank space/gap between lines 12 & 13 
- [ ] why does thundered have a diplomatic viz? (we don't have manuscript line breaks or any manuscript info really except the page breaks; place and considering do not have diplomatic viz, which is probably a good thing)

**Comment by amir-zeldes** [comment]
OK, YA 309 was an issue where the CSS does not play nicely if hi_rend=small spans multiple lines. As an easy fix, I just gave each line its own hi_rend=small.

Thundered has lb_n annotations, so it assumed it should get dipl, but it's no problem turning it off. Should those be edition lines instead?

**Comment by ctschroeder** [comment]
Thanks. Ok let me check Thundered. I don't remember off the top of my head. I thought I fixed all those but perhaps not. Amélineau definitely does NOT mark manuscript line breaks.

I have a few other documents to check tonight, as well, so please hold off on further steps.

**Comment by bkrawiec** [comment]
Here are some errors/problems I have noted in A22 YA 311-16


DIPLOMATIC


  1.  The title says "YA 311-12" but should say "YA 311-16"
  2.  All the ekthetics are slightly to the left of margin but were not made large (I checked the XML and it says ekthetic large)
  3.  YA 312 col a line 11 needs to be indented.
  4.  YA 314 col a line 2 should end at the second ϥ; what follows on that line is line 3 (error in XML)
  5.  YA 314 col a line 24 should end at ⲏ; what follows is a separate line (error in XML)
  6.  YA 315 col a line 12 needs to be indented
  7.  YA 315 col b line 13 remove extra bracket

ANALYTIC:

In Ch. 958, (2) and (3) some boxes are highlighted in yellow. Is this correct?

NORMALIZED:

Here it seems the bound groups are not bound in the normalization but segmented along piping.

________________________________

**Comment by ctschroeder** [comment]
@bkrawiec thanks so much for this detailed review of your document! I have a few questions and requests:

- [ ] YA 312 col 1 line 11 is missing in Gitdox. (There are no spans -- there are three cells in the lb_n column that aren't merged). Can you check rows 249-251 in Gitdox against the manuscript and set the line breaks? I think that may fix your number 3.. Thanks!
- [ ] re your numbers 4 & 5 I think you will need to check the line breaks against the manuscript and fix it in GitDox too. When you say that "what follows" is on ine three or the following line I don't know whether to add it to the following line or make a new line or what.  Thanks!!
- [ ] re 6 as with number 3 there is no span here. Could you check and fix in Gitdox also?
- [ ] re 7 which bracket? in GitDox in the TOK layer there is a bracket after the ϥ and a bracket after the ⲏ. In orig_group there is only a bracket after the ⲏ. Which one is "extra"?
- [ ] I don't understand what the problem is with the normalized view. The bound groups look correct to me. Can you add a bit more detail?

**Comment by ctschroeder** [comment]
@amir-zeldes 

- [ ] I don't know how to fix Becky's second problem above with the ekthetics not visualizing as large. The hi_rend layer in GitDox consistently has "ekthetic large" in the correct field

**Comment by ctschroeder** [comment]
Also @amir-zeldes Thundered is fixed in Gitdox. I'm still looking at Pistis Sophia

**Comment by bkrawiec** [comment]
I made all these fixes as noted.


For the extra bracket, it was not in orig_group but was on the tok level, so I removed it and hope that does it. The extra is/was between the ϥ and ⲏ.


Whatever I was seeing in the normalized view is no longer there.

________________________________

**Comment by ctschroeder** [comment]
@lancealanmartin I am sorry to bother you -- are the line breaks in Pistis Sophia from Marcion or from the manuscript? Thanks so much.

**Comment by amir-zeldes** [comment]
I'm 99% sure the line breaks in Pistis are from the edition - Marcion doesn't have MS breaks, so I don't see where we would have gotten them from.

**Comment by amir-zeldes** [comment]
Large rendering is now fixed, you can take a look in ANNIS and I'll aim to have them in CTS later today too.

**Comment by lancealanmartin** [comment]
No problem whatsoever! The line breaks (lb_n, right?) match Marcion. I am not sure if the Marcion line breaks follow the manuscript or not.

**Comment by ctschroeder** [comment]
large rendering looks good. It appears that the line breaks are from the Petermann edtion, so I am now changing all the layer names from lb_n to ed_line_n. I should be done this afternoon.

**Comment by ctschroeder** [comment]
ok pistis sophia I think is ready

**Comment by amir-zeldes** [comment]
OK, everything is up to date in ANNIS and in CTS! If it all looks presentable I think we can announce end of day (I'll hold off on the GH release zip for a few more days, and still need to update CDO examples and tools)

**Comment by ctschroeder** [comment]
Thanks so much. 

I’ll look into this more this afternoon and change the lb_n layer names as appropriate in all docs. It’s going to be a couple hours until I get to it and to check the large rendering.

**Comment by amir-zeldes** [comment]
I think this was fine in the release, no? If so I can make the release zip in GH.

**Comment by ctschroeder** [comment]
I gotta be honest — I have no idea if I did this or not. (I’m usually pretty good at following up though.) Either way the release is the release, and if it’s not fixed it will wait for the next one. Thanks for finishing this up, Amir!

**Comment by amir-zeldes** [comment]
Done! Closing...
