### ISSUE TITLE
Spring/Summer 2023 release thread

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#97]
## Timeline
Primary editors work freezes 1 September 2023
Data freeze some point in September TBA
Publication September/October

### Tentative Corpora
- [x] AP (do not check off until [this issue](https://github.com/CopticScriptorium/ap-dev/issues/94) is complete)
- [x] Besa (somebody needs to check ch/v against Kuhn @bkrawiec @cluckmarq @LCBM0828 )
- [x] Shenoute A22 do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-a22-dev/issues/56) is complete)
- [x] My Heart is Crushed (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/2) is complete)
- [x] Canons 9 shenoute.true and shenoute.considering (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-canons9-dev/issues/4) is complete)
- [x] Unplaced Fragment(s) shenoute.uncertain (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-unplaced-dev/issues/1) is complete)

Corpora with corrections but previously published
- [x] John of Constantinople (Marcion, corrections)
- [x] Dormition of John (updated metadata)
- [x] Life Eustathius.theopiste (Marcion corrections)
- [x] Life of Onnophrius (Marcion, corrections)
- [x] Pistis sophia
- [x] 1 Cor
- [x] Mark
- [x] Fox
- [x] Dirt

note: version number and date in documents and corpus version number and date will be updated by @amir-zeldes  for all

### Other possible corpora

- Other Marcion?
        - Encomium on St John the Baptist
        - Theophilus on Repentence & Continence (?)
        - Resurrection of Jesus Christ

- more Amélineau (incorporated above)

## For Next Time
- [ ] So Listen (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/1) is complete)
- [ ] This Great House (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-canons7-dev/issues/2) is complete)
- [ ] Tito's editions?
    - [ ] Encomium on Raphael
    - [ ] Cyril ?
- [ ] If Everyone Errs (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-canons7-dev/issues/1) is complete)
- [ ] Who But God is the Witness (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/3) is complete)
- [ ] My Heart is Crushed  (do not check off until [this issue](https://github.com/CopticScriptorium/shenoute-canons8-dev/issues/4) is complete)
- [ ] Gospel of Thomas
        ~- [ ] @m-linssen 's edition~
        - [ ] @babelalexandria's edition
- [ ] Marcion Nag Hammadi
- [ ] New Coptic OT edition?

**Comment by ctschroeder** [comment]
@bkrawiec @babelAlexandria @cluckmarq @m-linssen @PhilippeZaher @ChristineAyad1  Thank you so much for volunteering for the project! the deadline for material for our next release is 1 September 2023. This means that for anything you're working on to be published in Fall 2023 (our next release, probably the last of the calendar year), your work needs to be done and submitted to me for final editorial review. For folks who have just started working on the project in the past couple of years, you probably will want me to review your work once before that point, as well. This is a hard deadline.

@LCBM0828 & @aharrin this is largely irrelevant for you because of the timeline of your contract, but keeping you up to date nonetheless.

Thank you everyone for your work!

**Comment by ctschroeder** [comment]
adding @Anri3006 to the thread -- we have so many people on the project right now, I can't keep track!

**Comment by ctschroeder** [comment]
- [ ] @ctschroeder needs to check if Nina S's material is on the list

**Comment by ctschroeder** [comment]
BK & CLM have checked Besa -- one document left from LCBM

**Comment by ctschroeder** [comment]
@amir-zeldes Besa corpus is ready to go

**Comment by ctschroeder** [comment]
@amir-zeldes is the corpus version_date also added automatically at release?

**Comment by amir-zeldes** [comment]
yes, that's no problem

**Comment by ctschroeder** [comment]
@amir-zeldes I think we are all set with the scheduled corpora. The last one, shenoute.crushed is done -- there are two docs in there that are not ready, so only publish the docs set "to_publish". :)

**Comment by amir-zeldes** [comment]
OK, this took a while, but I now have a first cut in ANNIS which you can preview - it's not live on GH or CTS yet, just in ANNIS. I noticed some of the new AP look messed up in diplomatic, for example 71, and then I saw it has lb instead of lb_n as a column. There are also issues with pistis sophia I need to investigate. I'm going to stop now for tonight, but if someone could check out the diplomatic view of the new AP in ANNIS and flag broken ones for me that would be great! (if it's just lb for lb_n, feel free to fix in GD and commit any fixes)

Will continue tomorrow...

**Comment by LCBM0828** [comment]
@amir-zeldes I am looking now through the AP in ANNIS. AP71 has a lb_n in GD. I'll go through and make of list of those that seem to be messed up in ANNIS/diplomatic view.

**Comment by LCBM0828** [comment]
Still a question: 
AP.071.n244.child
not sure what is going on with the error here. the column is lb_n. 

Did not edit but see an error: 
AP.020.n373.failings
AP.021.n149.lentils
note: I see that the columns are labeled line not lb_n for both of these. I did not change, these are both published and I didn’t know if that would mess things up. 

AP I edited/changed lb to lb_n + committed in GD:
AP.065.n239.sober
AP.066.n240.spiritual
AP.068.n387.salvation
AP.069.n242.asceticism
AP.072.n245.discipleship
AP.093.n279.death

+I edited AP.047.n200.temptation—one line was messed up; missing MS lb. I fixed and committed in GD.

**Comment by amir-zeldes** [comment]
Thanks @LCBM0828 ! Yes, I already fixed 71 but not uploaded it yet, because I realized there were more with issues. The issue with 20-21 is probably 'line', I will fix that and upload to ANNIS to re-inspect.

**Comment by ctschroeder** [comment]
I’ve been in meetings all day. Do you need me to check tonight?

Sent from my iPhone

**Comment by amir-zeldes** [comment]
I think we are all good now - ANNIS, CTS and GH are all up to date so the release is more or less complete! The remaining steps are to do a blog post, and the things I do after a few days once no one flags an issue: mint a GH release archive with the current version number, and tool updates (incl. CDO example generation).
